# Site settings
title       : Blog
author      : Lsong
email       : blog@lsong.org
description : Open Source Software & Hardware
url         : https://blog.lsong.org
permalink   : /:year/:month/:title.html
icon        : https://lsong.org/icon.png
# Build settings
analytics   : 'UA-42621148-5'
# Social Network
github      : 'lsongdev'
twitter     : 'lsongdev'
facebook    : 'lsongdev'
google      : '+LiusongLsong'

# Podcasts
# http://podba.se/validate
explicit: "no"
# http://itunespartner.apple.com/podcasts/overview#_Toc526931698
category:
  Technology:
    - Software How-To
    - Tech News
    - Gadgets
